name: Publish

on:
  push:
    branches:
      - main
    paths:
      - ".changeset/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10.11.0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          # scope: "@victor-template"

      - name: Install dependencies
        run: pnpm install

      # - name: Create Release PR or Publish
      #   uses: changesets/action@v1
      #   with:
      #     version: pnpm ci:version
      #     publish: pnpm ci:release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: pnpm build

      - name: git status
        run: git status

      - name: npm publish
        # run: pnpm publish --access public
        run: pnpm publish
